package pub.frames;

import java.awt.BorderLayout;
import javax.swing.JPanel;

public class ClienteMenu extends javax.swing.JFrame {

    public static void showPg(JPanel pg) {
    pg.setSize(580,700);
    pg.setLocation(0,0);
    Content.removeAll();
    Content.add(pg, BorderLayout.CENTER);
    Content.revalidate();
    Content.repaint();
  }

  public ClienteMenu() {
    initComponents();
    setLocationRelativeTo(null);
    toggleMenu.setVisible(false);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Cabeza = new javax.swing.JPanel();
        pubIcon = new javax.swing.JLabel();
        toggleButton = new javax.swing.JToggleButton();
        toggleMenu = new javax.swing.JPanel();
        btnFood = new javax.swing.JButton();
        btnBeer = new javax.swing.JButton();
        btnWine = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabeza.setBackground(new java.awt.Color(27, 31, 37));

        pubIcon.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 1, 48)); // NOI18N
        pubIcon.setForeground(new java.awt.Color(73, 168, 245));
        pubIcon.setText("NP");

        toggleButton.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 48)); // NOI18N
        toggleButton.setForeground(new java.awt.Color(255, 255, 255));
        toggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_down.png"))); // NOI18N
        toggleButton.setActionCommand("x");
        toggleButton.setBorder(null);
        toggleButton.setBorderPainted(false);
        toggleButton.setContentAreaFilled(false);
        toggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CabezaLayout = new javax.swing.GroupLayout(Cabeza);
        Cabeza.setLayout(CabezaLayout);
        CabezaLayout.setHorizontalGroup(
            CabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabezaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pubIcon)
                .addGap(14, 14, 14))
        );
        CabezaLayout.setVerticalGroup(
            CabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CabezaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pubIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Cabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        toggleMenu.setBackground(new java.awt.Color(11, 73, 110));

        btnFood.setBackground(new java.awt.Color(19, 119, 180));
        btnFood.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnFood.setForeground(new java.awt.Color(153, 201, 219));
        btnFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient_hamburger.png"))); // NOI18N
        btnFood.setText("Comidas");
        btnFood.setBorderPainted(false);
        btnFood.setContentAreaFilled(false);
        btnFood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFood.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFood.setIconTextGap(18);
        btnFood.setVerifyInputWhenFocusTarget(false);
        btnFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFoodMouseExited(evt);
            }
        });
        btnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodActionPerformed(evt);
            }
        });

        btnBeer.setBackground(new java.awt.Color(19, 119, 180));
        btnBeer.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnBeer.setForeground(new java.awt.Color(153, 201, 219));
        btnBeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient_beer.png"))); // NOI18N
        btnBeer.setText("Cervezas");
        btnBeer.setContentAreaFilled(false);
        btnBeer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeer.setDefaultCapable(false);
        btnBeer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeer.setIconTextGap(15);
        btnBeer.setVerifyInputWhenFocusTarget(false);
        btnBeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBeerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBeerMouseExited(evt);
            }
        });
        btnBeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeerActionPerformed(evt);
            }
        });

        btnWine.setBackground(new java.awt.Color(19, 119, 180));
        btnWine.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnWine.setForeground(new java.awt.Color(153, 201, 219));
        btnWine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient_wine.png"))); // NOI18N
        btnWine.setText("Vinos & Licores");
        btnWine.setBorderPainted(false);
        btnWine.setContentAreaFilled(false);
        btnWine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnWine.setIconTextGap(12);
        btnWine.setVerifyInputWhenFocusTarget(false);
        btnWine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWineMouseExited(evt);
            }
        });
        btnWine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWineActionPerformed(evt);
            }
        });

        btnOut.setBackground(new java.awt.Color(19, 119, 180));
        btnOut.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnOut.setForeground(new java.awt.Color(153, 201, 219));
        btnOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gradient_logout.png"))); // NOI18N
        btnOut.setText("Salir");
        btnOut.setBorderPainted(false);
        btnOut.setContentAreaFilled(false);
        btnOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOut.setIconTextGap(15);
        btnOut.setVerifyInputWhenFocusTarget(false);
        btnOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOutMouseExited(evt);
            }
        });
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toggleMenuLayout = new javax.swing.GroupLayout(toggleMenu);
        toggleMenu.setLayout(toggleMenuLayout);
        toggleMenuLayout.setHorizontalGroup(
            toggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(toggleMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toggleMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(toggleMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        toggleMenuLayout.setVerticalGroup(
            toggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toggleMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWine, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFood, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOut)
                .addGap(6, 6, 6))
        );

        getContentPane().add(toggleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 580, -1));

        Content.setBackground(new java.awt.Color(27, 31, 37));

        txtTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(73, 168, 245));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Welcome");

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );

        getContentPane().add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 580, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFoodActionPerformed

    private void btnBeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeerActionPerformed
        pgClientBeer pg = new pgClientBeer();
        toggleMenu.setVisible(false);
        toggleButton.setSelected(false);
        toggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_down.png")));
        Cabeza.setBackground(new java.awt.Color(27,31,37));
        showPg(pg);
    }//GEN-LAST:event_btnBeerActionPerformed

    private void btnWineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWineActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
      Ingresar f = new Ingresar();
      f.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnOutActionPerformed

    private void toggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonActionPerformed
        if (toggleButton.isSelected()) {
            toggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_up.png")));
            Cabeza.setBackground(new java.awt.Color(11,73,110));
            toggleMenu.setVisible(true);
        } else {
            toggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_down.png")));
            Cabeza.setBackground(new java.awt.Color(27,31,37));
            toggleMenu.setVisible(false);
        }
    }//GEN-LAST:event_toggleButtonActionPerformed

    private void btnBeerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeerMouseEntered
        btnBeer.setForeground(new java.awt.Color(120, 154, 168));
    }//GEN-LAST:event_btnBeerMouseEntered

    private void btnBeerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeerMouseExited
        btnBeer.setForeground(new java.awt.Color(153, 201, 219));
    }//GEN-LAST:event_btnBeerMouseExited

    private void btnWineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWineMouseEntered
        btnWine.setForeground(new java.awt.Color(120, 154, 168));
    }//GEN-LAST:event_btnWineMouseEntered

    private void btnWineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWineMouseExited
        btnWine.setForeground(new java.awt.Color(153, 201, 219));
    }//GEN-LAST:event_btnWineMouseExited

    private void btnFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodMouseEntered
        btnFood.setForeground(new java.awt.Color(120, 154, 168));
    }//GEN-LAST:event_btnFoodMouseEntered

    private void btnFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodMouseExited
        btnFood.setForeground(new java.awt.Color(153, 201, 219));
    }//GEN-LAST:event_btnFoodMouseExited

    private void btnOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOutMouseEntered
        btnOut.setForeground(new java.awt.Color(120, 154, 168));
    }//GEN-LAST:event_btnOutMouseEntered

    private void btnOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOutMouseExited
        btnOut.setForeground(new java.awt.Color(153, 201, 219));
    }//GEN-LAST:event_btnOutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cabeza;
    public static javax.swing.JPanel Content;
    private javax.swing.JButton btnBeer;
    private javax.swing.JButton btnFood;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnWine;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel pubIcon;
    private javax.swing.JToggleButton toggleButton;
    private javax.swing.JPanel toggleMenu;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
