/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pub.frames;

/**
 *
 * @author gerry
 */
public class pgClientBeer extends javax.swing.JPanel {

    /**
     * Creates new form pgClientBeer
     */
    public pgClientBeer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JLabel();
        txtContador = new javax.swing.JLabel();
        txtContador1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JLabel();
        txtContador2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        img3 = new javax.swing.JLabel();
        txtName3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        txtName4 = new javax.swing.JLabel();
        txtContador3 = new javax.swing.JLabel();
        txtContador4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        txtName5 = new javax.swing.JLabel();
        txtContador5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMinus6 = new javax.swing.JButton();
        btnPlus6 = new javax.swing.JButton();
        btnMinus7 = new javax.swing.JButton();
        btnPlus7 = new javax.swing.JButton();
        btnMinus8 = new javax.swing.JButton();
        btnPlus8 = new javax.swing.JButton();
        btnMinus9 = new javax.swing.JButton();
        btnPlus9 = new javax.swing.JButton();
        btnMinus10 = new javax.swing.JButton();
        btnPlus10 = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 31, 37));
        setPreferredSize(new java.awt.Dimension(580, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beer_corona.png"))); // NOI18N
        add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, 150));

        btnMinus.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(73, 168, 245));
        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnMinus.setText("");
        btnMinus.setBorder(null);
        btnMinus.setBorderPainted(false);
        btnMinus.setContentAreaFilled(false);
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 40, 40));

        btnPlus.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(73, 168, 245));
        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnPlus.setText("");
        btnPlus.setBorder(null);
        btnPlus.setBorderPainted(false);
        btnPlus.setContentAreaFilled(false);
        btnPlus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 40, 40));

        txtName.setForeground(new java.awt.Color(204, 204, 204));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("Victoria 355ml");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 100, -1));

        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beer_victoria.png"))); // NOI18N
        add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 150));

        txtName1.setForeground(new java.awt.Color(204, 204, 204));
        txtName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName1.setText("Corona extra 355ml");
        add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 130, -1));

        txtContador.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtContador.setForeground(new java.awt.Color(73, 168, 245));
        txtContador.setText("1");
        add(txtContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 10, -1));

        txtContador1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtContador1.setForeground(new java.awt.Color(73, 168, 245));
        txtContador1.setText("1");
        add(txtContador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 10, -1));

        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beer_pacifico.png"))); // NOI18N
        add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 150));

        txtName2.setForeground(new java.awt.Color(204, 204, 204));
        txtName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName2.setText("Pacifico 355ml");
        add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 100, -1));

        txtContador2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtContador2.setForeground(new java.awt.Color(73, 168, 245));
        txtContador2.setText("1");
        add(txtContador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 10, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 580, 20));

        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beer_modelo.png"))); // NOI18N
        add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 60, 150));

        txtName3.setForeground(new java.awt.Color(204, 204, 204));
        txtName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName3.setText("Miller 945ml");
        add(txtName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 100, -1));

        img4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beer_miller.png"))); // NOI18N
        add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 50, 150));

        txtName4.setForeground(new java.awt.Color(204, 204, 204));
        txtName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName4.setText("Modelo especial 355ml");
        add(txtName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 150, -1));

        txtContador3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtContador3.setForeground(new java.awt.Color(73, 168, 245));
        txtContador3.setText("1");
        add(txtContador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 10, -1));

        txtContador4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtContador4.setForeground(new java.awt.Color(73, 168, 245));
        txtContador4.setText("1");
        add(txtContador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, 10, -1));

        img5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beer_heineken.png"))); // NOI18N
        add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 50, 150));

        txtName5.setForeground(new java.awt.Color(204, 204, 204));
        txtName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName5.setText("Heineken 355ml");
        add(txtName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 120, -1));

        txtContador5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtContador5.setForeground(new java.awt.Color(73, 168, 245));
        txtContador5.setText("1");
        add(txtContador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 10, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 183, 174));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CERVEZAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 220, 70));

        btnMinus6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMinus6.setForeground(new java.awt.Color(73, 168, 245));
        btnMinus6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnMinus6.setText("");
        btnMinus6.setBorder(null);
        btnMinus6.setBorderPainted(false);
        btnMinus6.setContentAreaFilled(false);
        btnMinus6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        add(btnMinus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, 40));

        btnPlus6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPlus6.setForeground(new java.awt.Color(73, 168, 245));
        btnPlus6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnPlus6.setText("");
        btnPlus6.setBorder(null);
        btnPlus6.setBorderPainted(false);
        btnPlus6.setContentAreaFilled(false);
        btnPlus6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        btnPlus6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus6ActionPerformed(evt);
            }
        });
        add(btnPlus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 40, 40));

        btnMinus7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMinus7.setForeground(new java.awt.Color(73, 168, 245));
        btnMinus7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnMinus7.setText("");
        btnMinus7.setBorder(null);
        btnMinus7.setBorderPainted(false);
        btnMinus7.setContentAreaFilled(false);
        btnMinus7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        add(btnMinus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 40, 40));

        btnPlus7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPlus7.setForeground(new java.awt.Color(73, 168, 245));
        btnPlus7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnPlus7.setText("");
        btnPlus7.setBorder(null);
        btnPlus7.setBorderPainted(false);
        btnPlus7.setContentAreaFilled(false);
        btnPlus7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        btnPlus7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus7ActionPerformed(evt);
            }
        });
        add(btnPlus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 40, 40));

        btnMinus8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMinus8.setForeground(new java.awt.Color(73, 168, 245));
        btnMinus8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnMinus8.setText("");
        btnMinus8.setBorder(null);
        btnMinus8.setBorderPainted(false);
        btnMinus8.setContentAreaFilled(false);
        btnMinus8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        add(btnMinus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 40, 40));

        btnPlus8.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPlus8.setForeground(new java.awt.Color(73, 168, 245));
        btnPlus8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnPlus8.setText("");
        btnPlus8.setBorder(null);
        btnPlus8.setBorderPainted(false);
        btnPlus8.setContentAreaFilled(false);
        btnPlus8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        btnPlus8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus8ActionPerformed(evt);
            }
        });
        add(btnPlus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 40, 40));

        btnMinus9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMinus9.setForeground(new java.awt.Color(73, 168, 245));
        btnMinus9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnMinus9.setText("");
        btnMinus9.setBorder(null);
        btnMinus9.setBorderPainted(false);
        btnMinus9.setContentAreaFilled(false);
        btnMinus9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        add(btnMinus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 40, 40));

        btnPlus9.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPlus9.setForeground(new java.awt.Color(73, 168, 245));
        btnPlus9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnPlus9.setText("");
        btnPlus9.setBorder(null);
        btnPlus9.setBorderPainted(false);
        btnPlus9.setContentAreaFilled(false);
        btnPlus9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        btnPlus9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus9ActionPerformed(evt);
            }
        });
        add(btnPlus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 40, 40));

        btnMinus10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMinus10.setForeground(new java.awt.Color(73, 168, 245));
        btnMinus10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnMinus10.setText("");
        btnMinus10.setBorder(null);
        btnMinus10.setBorderPainted(false);
        btnMinus10.setContentAreaFilled(false);
        btnMinus10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        add(btnMinus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 40, 40));

        btnPlus10.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnPlus10.setForeground(new java.awt.Color(73, 168, 245));
        btnPlus10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_blue.png"))); // NOI18N
        btnPlus10.setText("");
        btnPlus10.setBorder(null);
        btnPlus10.setBorderPainted(false);
        btnPlus10.setContentAreaFilled(false);
        btnPlus10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1_pressed.png"))); // NOI18N
        btnPlus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus10ActionPerformed(evt);
            }
        });
        add(btnPlus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnPlus6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlus6ActionPerformed

    private void btnPlus7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlus7ActionPerformed

    private void btnPlus8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlus8ActionPerformed

    private void btnPlus9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlus9ActionPerformed

    private void btnPlus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlus10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMinus10;
    private javax.swing.JButton btnMinus6;
    private javax.swing.JButton btnMinus7;
    private javax.swing.JButton btnMinus8;
    private javax.swing.JButton btnMinus9;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlus10;
    private javax.swing.JButton btnPlus6;
    private javax.swing.JButton btnPlus7;
    private javax.swing.JButton btnPlus8;
    private javax.swing.JButton btnPlus9;
    private javax.swing.JLabel img;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtContador;
    private javax.swing.JLabel txtContador1;
    private javax.swing.JLabel txtContador2;
    private javax.swing.JLabel txtContador3;
    private javax.swing.JLabel txtContador4;
    private javax.swing.JLabel txtContador5;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtName1;
    private javax.swing.JLabel txtName2;
    private javax.swing.JLabel txtName3;
    private javax.swing.JLabel txtName4;
    private javax.swing.JLabel txtName5;
    // End of variables declaration//GEN-END:variables
}
