package pub.frames;

import pub.Comida;

public class pgRegistrarComida extends javax.swing.JPanel {

  public static Comida.Pila pila = new Comida.Pila();
  public pgRegistrarComida() {
    initComponents();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        txName = new javax.swing.JLabel();
        txTipo = new javax.swing.JLabel();
        txPrecio = new javax.swing.JLabel();
        txCal = new javax.swing.JLabel();
        txSize = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfTipo = new javax.swing.JTextField();
        jtfPrecio = new javax.swing.JTextField();
        jtfCal = new javax.swing.JTextField();
        jtfSize = new javax.swing.JTextField();
        bRegistrar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Mensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 31, 37));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(188, 183, 174));
        Title.setFont(new java.awt.Font("SF Pro Display", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(188, 183, 174));
        Title.setText("REGISTRO DE COMIDAS");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        txName.setBackground(new java.awt.Color(188, 183, 174));
        txName.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        txName.setForeground(new java.awt.Color(188, 183, 174));
        txName.setText("Nombre del Plato:");
        add(txName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txTipo.setBackground(new java.awt.Color(188, 183, 174));
        txTipo.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        txTipo.setForeground(new java.awt.Color(188, 183, 174));
        txTipo.setText("Tipo de platillo:");
        add(txTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txPrecio.setBackground(new java.awt.Color(188, 183, 174));
        txPrecio.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        txPrecio.setForeground(new java.awt.Color(188, 183, 174));
        txPrecio.setText("Precio del platillo:");
        add(txPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txCal.setBackground(new java.awt.Color(188, 183, 174));
        txCal.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        txCal.setForeground(new java.awt.Color(188, 183, 174));
        txCal.setText("Cantidad de calorias:");
        add(txCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txSize.setBackground(new java.awt.Color(188, 183, 174));
        txSize.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        txSize.setForeground(new java.awt.Color(188, 183, 174));
        txSize.setText("Tamaño:");
        add(txSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jtfNombre.setBackground(new java.awt.Color(27, 31, 37));
        jtfNombre.setFont(new java.awt.Font("SF Pro", 0, 14)); // NOI18N
        jtfNombre.setForeground(new java.awt.Color(204, 204, 204));
        jtfNombre.setBorder(null);
        add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 530, -1));

        jtfTipo.setBackground(new java.awt.Color(27, 31, 37));
        jtfTipo.setFont(new java.awt.Font("SF Pro", 0, 14)); // NOI18N
        jtfTipo.setForeground(new java.awt.Color(204, 204, 204));
        jtfTipo.setBorder(null);
        add(jtfTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 530, -1));

        jtfPrecio.setBackground(new java.awt.Color(27, 31, 37));
        jtfPrecio.setFont(new java.awt.Font("SF Pro", 0, 14)); // NOI18N
        jtfPrecio.setForeground(new java.awt.Color(204, 204, 204));
        jtfPrecio.setBorder(null);
        add(jtfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 530, -1));

        jtfCal.setBackground(new java.awt.Color(27, 31, 37));
        jtfCal.setFont(new java.awt.Font("SF Pro", 0, 14)); // NOI18N
        jtfCal.setForeground(new java.awt.Color(204, 204, 204));
        jtfCal.setBorder(null);
        add(jtfCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 530, -1));

        jtfSize.setBackground(new java.awt.Color(27, 31, 37));
        jtfSize.setFont(new java.awt.Font("SF Pro", 0, 14)); // NOI18N
        jtfSize.setForeground(new java.awt.Color(204, 204, 204));
        jtfSize.setBorder(null);
        add(jtfSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 530, -1));

        bRegistrar.setBackground(new java.awt.Color(28, 51, 132));
        bRegistrar.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        bRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1Large_gradient.png"))); // NOI18N
        bRegistrar.setText("REGISTRAR");
        bRegistrar.setBorder(null);
        bRegistrar.setBorderPainted(false);
        bRegistrar.setContentAreaFilled(false);
        bRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1Large_gradientPressed.png"))); // NOI18N
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 200, 60));

        bEliminar.setBackground(new java.awt.Color(28, 51, 132));
        bEliminar.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1Large_gradient.png"))); // NOI18N
        bEliminar.setText("ELIMINAR");
        bEliminar.setBorder(null);
        bEliminar.setBorderPainted(false);
        bEliminar.setContentAreaFilled(false);
        bEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1Large_gradientPressed.png"))); // NOI18N
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 200, 60));

        bVolver.setBackground(new java.awt.Color(28, 51, 132));
        bVolver.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        bVolver.setForeground(new java.awt.Color(255, 255, 255));
        bVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1Large_gradient.png"))); // NOI18N
        bVolver.setText("VOLVER");
        bVolver.setBorder(null);
        bVolver.setBorderPainted(false);
        bVolver.setContentAreaFilled(false);
        bVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn1Large_gradientPressed.png"))); // NOI18N
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 200, 60));

        jSeparator1.setForeground(new java.awt.Color(73, 168, 245));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 530, -1));

        jSeparator2.setForeground(new java.awt.Color(73, 168, 245));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 530, 10));

        jSeparator3.setForeground(new java.awt.Color(73, 168, 245));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 530, 10));

        jSeparator4.setForeground(new java.awt.Color(73, 168, 245));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 530, 10));

        jSeparator5.setForeground(new java.awt.Color(73, 168, 245));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 530, 10));
        add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 720, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wings.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 290, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hamburger.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 290, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
      bVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
      pgInicio pg = new pgInicio();
      EmpleadoMenu.showPanel(pg);
      this.setVisible(false);
    }//GEN-LAST:event_bVolverActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
      bRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
      pila.push(jtfNombre.getText(),jtfTipo.getText(),Integer.parseInt(jtfPrecio.getText()),
              Integer.parseInt(jtfCal.getText()), jtfSize.getText());
      Mensaje.setForeground(new java.awt.Color(39,237,33));
      Mensaje.setText("Platillo registrado satisfactoriamente");
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
      bEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
      pila.pop();
      Mensaje.setForeground(new java.awt.Color(204, 0, 0));
      Mensaje.setText("Usuario eliminado");
    }//GEN-LAST:event_bEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel Title;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jtfCal;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfSize;
    private javax.swing.JTextField jtfTipo;
    private javax.swing.JLabel txCal;
    private javax.swing.JLabel txName;
    private javax.swing.JLabel txPrecio;
    private javax.swing.JLabel txSize;
    private javax.swing.JLabel txTipo;
    // End of variables declaration//GEN-END:variables
}
